fixtures:
  # use the forge modules so we can easily pin to a specific version
  forge_modules:
    firewall:
      repo: "puppetlabs/firewall"
      ref: "1.2.0"
    git: "puppetlabs/git"
    java:
      repo: "puppetlabs/java"
      ref: "1.2.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "3.0.0"
    stdlib: "puppetlabs/stdlib"
#  repositories:
#    firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
#    java:
#      repo: "git://github.com/puppetlabs/puppetlabs-java.git"
#      ref: "1.2.0"
#    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
#    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    gerrit: "#{source_dir}"
